#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "panoramax-review"
name = "Panoramax Review"
description.en = "Review street-level imagery from Panoramax: flag errors, track issues, and manage picture quality"
description.fr = "Examinez les images de rue de Panoramax : signalez les erreurs, suivez les problèmes et gérez la qualité des photos"
description.nl = "Beoordeel straatbeelden van Panoramax: markeer fouten, volg problemen en beheer beeldkwaliteit"

version = "1.1.1~ynh1"

maintainers = []

[upstream]
license = "MIT"
code = "https://github.com/Thib-ai/panoramax-review"
admindoc = "https://github.com/Thib-ai/panoramax-review"

[integration]
yunohost = ">= 11.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = true

disk = "50M"
ram.build = "300M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/review"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]

    [resources.sources.main]
    url = "https://github.com/Thib-ai/panoramax-review/archive/refs/tags/v1.1.1.tar.gz"
    sha256 = "124c85e30455ec64e880b89b61ebf3db76e0802abdda9b5cf40d2141ef96cf0a"
    in_subdir = true
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]
    main.default = 4983

    [resources.permissions]
    main.url = "/"
    main.auth_header = true

    [resources.nodejs]
    version = "22"

    [resources.apt]
    packages = "build-essential, python3"
